spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:5173"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - "*"
                allow-credentials: true

server:
  port: 8080

services:
  backend:
    url: ${BACKEND_URL:http://localhost:8081}